// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"
	model "golang-training/repository/model"

	mock "github.com/stretchr/testify/mock"
)

// Category is an autogenerated mock type for the Category type
type Category struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, doc
func (_m *Category) Create(ctx context.Context, doc *model.Category) error {
	ret := _m.Called(ctx, doc)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Category) error); ok {
		r0 = rf(ctx, doc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, uuid
func (_m *Category) Find(ctx context.Context, uuid string) (*model.Category, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Category, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Category); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategory creates a new instance of Category. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategory(t interface {
	mock.TestingT
	Cleanup(func())
}) *Category {
	mock := &Category{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
